### ISSUE TITLE
Change/Add Global Labels

### ISSUE THREAD

**Issue by inginheiiro** [adeotek/Serilog.Sinks.GrafanaLoki#10]
Hi,

Great plugin, thanks.
Can i add/remove/update a global label using and approach like LogContext.PushProperty ?

thanks

**Comment by adeotek** [comment]
Hi @inginheiiro, first of all, sorry for the late response.
Regarding labels, the Global Labels are intended to be global and fixed (all Global Labels will be present on every Log Stream sent to Loki). If you want to add contextual labels, you can do it through `LogContext.PushProperty`:
`
using (LogContext.PushProperty("ALabel", "ALabelValue"))
{
    log.Information("Info with ALabel");
    log.Warning("Warning with ALabel");
}
`
In this case the `ALabel` will be present only for the 2 Log Events encapsulated in the using statement.

Hope it is helpful.
