### ISSUE TITLE
Make single quotes for string property optional

### ISSUE THREAD

**Issue by Janry** [adeotek/Serilog.Sinks.GrafanaLoki#15]
Hi.
`
I have problem with single quotes. In code you replace all """ to "'". Can you please make this replace optional. I need just empty string for this. Because for example enum.SomeValue convert to "SomeValue", but string "SomeValue" to "'SomeValue'" and it's not looks like good.
I solved my problem with ILogEventEnricher and LogEventPropertyValue inherit my log event property from ScalarValue and override Render. But with parameter in appsettings.json will be better.
By the way global constant string labels work fine without single quotes escape.

Thank you.

**Comment by adeotek** [comment]
Hi @Janry,

I took your suggestion, and I've added a new configuration option called `propertiesStringDelimiter`, which allows you to override the default properties string delimiter "`" with any other one or with an empty string (see README.md).

This will be included in the next release, which should be published in the next few days.

Thank you

**Comment by adeotek** [comment]
Resolved in v1.1.2
