### ISSUE TITLE
Bad request errors clogs the sink

### ISSUE THREAD

**Issue by montoner0** [adeotek/Serilog.Sinks.GrafanaLoki#16]
The current retry policy incorrectly processes `400 bad request` validation errors from Loki, which are [non-retryable](https://grafana.com/docs/loki/latest/operations/request-validation-rate-limits/#validation-errors), therefore effectively clogs the sink until the whole app restarted. 
E. g. if Loki returns `label_value_too_long` or any other validation error, the sink will try to re-send the invalid stream again and again thus preventing all subsequent messages from sending.

**Comment by adeotek** [comment]
Thanks @montoner0, I will look into it as soon as possible.

**Comment by adeotek** [comment]
Resolved in v1.1.2

**Comment by montoner0** [comment]
Thanks for the fix though I don't think it's the best solution to skip a whole batch because of a single "bad" message...

**Comment by adeotek** [comment]
Hi @montoner0,

This is just a quick fix, not a permanent solution. I will further investigate how bad events can be singled out and removed from the batch before retrying.

Thank you
