### ISSUE TITLE
Dear author： I’d like to know that how to use serilog.loki to establish a customizing client to make an index for writing logs as Elasticsearch.

### ISSUE THREAD

**Issue by qiqistart** [adeotek/Serilog.Sinks.GrafanaLoki#9]

**Comment by huzitao** [comment]
Dear author： I’d like to know that how to use serilog.loki to establish a customizing client to make an index for writing logs as Elasticsearch.

**Comment by adeotek** [comment]
Hi @huzitao, I don't really understand your question. 
If you want to use Elasticsearch to store Loki indexes, please check the official Grafana Loki documentation [here](https://grafana.com/docs/loki/latest/storage/).
